# Agent Configuration - Unified Architecture
# 
# agent_mode: Controls the overall agent system mode
#   - "single": Use a single agent (no_rag or rag)
#   - "multi_agent": Use multi-agent system
#
# agent_type: Controls whether retrieval is enabled
#   - "no_rag": No retrieval capabilities (for both single and multi-agent modes)
#   - "rag": RAG capabilities with knowledge graph retrieval
#
# When agent_mode is "multi":
#   - If agent_type is "no_rag": Multi-agent system without retrieval (retriever agent disabled)
#   - If agent_type is "rag": Multi-agent system with retrieval (retriever agent enabled)
#
# Common settings are shared across all agent types:
#   - execution: LLM execution parameters
#   - retrieval: Knowledge graph retrieval parameters  
#   - system: Common system settings
#   - multi_step: Multi-step execution settings
#
# Multi-agent specific settings are under multi_agent section

# Agent configuration options
agent_mode: single      # Available modes: [single, multi, web]
agent_type: rag      # Type options: [no_rag, rag] 
                        # Note: Controls retrieval capabilities in all modes
                        # Web agent does not support this functionality

# Common execution settings (shared by all agents)
execution:
  max_context_length: 4000
  max_retries: 3
  max_tokens: 4000
  model_name: gpt-4o-mini
  require_citations: true
  require_reasoning: true
  response_format: json # structured, json
  retry_delay: 1.0
  temperature: 0.1
  timeout: 30
  
  # Image processing support
  support_images: true

# Common retrieval settings (used by RAG agents)
retrieval:
  expand_with_context: true
  include_neighbors: true
  max_hops: 3
  max_nodes: 10
  prefer_gold_nodes: true
  similarity_threshold: 0.7

# Common system settings
system:
  enable_evaluation: true
  enable_memory: true
  memory_size: 10
  verbose: false
  log_intermediate: false



# Multi-agent system configuration (only used when agent_mode is multi)
# Agent roles are automatically enabled/disabled based on agent_type
multi_agent:
  # System-level configuration
  max_iterations: 3
  confidence_threshold: 0.7
  verbose: true
  
  # Agent roles and their configurations
  # Note: retriever agent is automatically disabled when agent_type is "no_rag"
  agents:
    planner:
      model_name: gpt-4o-mini
      temperature: 0.1
      max_tokens: 1000
      timeout: 30
      max_retries: 3
      response_format: json
      retrieval:
        max_nodes: 10
        max_hops: 3
        similarity_threshold: 0.7
      enable_evaluation: true
      verbose: false
    
    retriever:
      # This agent is automatically disabled when agent_type is "no_rag"
      model_name: gpt-4o-mini
      temperature: 0.0
      max_tokens: 500
      timeout: 30
      max_retries: 3
      response_format: json
      retrieval:
        max_nodes: 15
        max_hops: 2
        similarity_threshold: 0.8
      enable_evaluation: true
      verbose: false
    
    reasoner:
      model_name: gpt-4o-mini
      temperature: 0.1
      max_tokens: 1500
      timeout: 30
      max_retries: 3
      response_format: json
      retrieval:
        max_nodes: 10
        max_hops: 3
        similarity_threshold: 0.7
      enable_evaluation: true
      verbose: false
    
    verifier:
      model_name: gpt-4o-mini
      temperature: 0.0
      max_tokens: 800
      timeout: 30
      max_retries: 3
      response_format: json
      retrieval:
        max_nodes: 8
        max_hops: 2
        similarity_threshold: 0.8
      enable_evaluation: true
      verbose: false
    
    summarizer:
      model_name: gpt-4o-mini
      temperature: 0.1
      max_tokens: 1200
      timeout: 30
      max_retries: 3
      response_format: json
      retrieval:
        max_nodes: 10
        max_hops: 2
        similarity_threshold: 0.7
      enable_evaluation: true
      verbose: false


# Web Agent configuration (used when agent_mode is "web")
web_agent:
  # Browser Automation Configuration
  use_browser: true  # Enable real browser automation
  headless: true     # Run browser in headless mode
  timeout: 30        # Page load timeout
  wait_time: 1.0     # Wait time between actions
  
  # Web Evaluator Configuration
  evaluator:
    navigation_weight: 0.3
    interaction_weight: 0.3
    data_extraction_weight: 0.2
    behavior_similarity_weight: 0.2
    success_threshold: 0.7
  


