agent_type: no_rag
enable_evaluation: true
enable_memory: true
enable_multi_agent: true
execution:
  max_context_length: 4000
  max_retries: 3
  max_tokens: 4000
  model_name: gpt-4o-mini
  require_citations: true
  require_reasoning: true
  response_format: json # structured, json
  retry_delay: 1.0
  temperature: 0.1
  timeout: 30
executor_type: llm
log_intermediate: false
memory_size: 10
multi_step:
  decomposition_strategy: automatic
  enabled: true
  max_subtasks: 5
  subtask_timeout: 20
retrieval:
  expand_with_context: true
  include_neighbors: true
  max_hops: 3
  max_nodes: 10
  prefer_gold_nodes: true
  similarity_threshold: 0.7
retriever_type: hybrid
verbose: false

# Multi-agent system configuration
multi_agent:
  # System-level configuration
  enable_parallel_execution: false
  enable_agent_communication: true
  max_iterations: 3
  confidence_threshold: 0.7
  verbose: true
  log_agent_outputs: true
  
  # LLM model configuration for each agent
  planner_model: gpt-4o-mini
  retriever_model: gpt-4o-mini
  reasoner_model: gpt-4o-mini
  verifier_model: gpt-4o-mini
  summarizer_model: gpt-4o-mini
  
  # Execution configuration for each agent (optional, will override default settings)
  planner_config:
    execution:
      model_name: gpt-4o-mini
      temperature: 0.1
      max_tokens: 1000
      timeout: 30
      max_retries: 3
      response_format: json
    retrieval:
      max_nodes: 10
      max_hops: 3
      similarity_threshold: 0.7
    enable_evaluation: true
    verbose: false
  
  retriever_config:
    execution:
      model_name: gpt-4o-mini
      temperature: 0.0
      max_tokens: 500
      timeout: 30
      max_retries: 3
      response_format: json
    retrieval:
      max_nodes: 15
      max_hops: 2
      similarity_threshold: 0.8
    enable_evaluation: true
    verbose: false
  
  reasoner_config:
    execution:
      model_name: gpt-4o-mini
      temperature: 0.1
      max_tokens: 1500
      timeout: 30
      max_retries: 3
      response_format: json
    retrieval:
      max_nodes: 10
      max_hops: 3
      similarity_threshold: 0.7
    enable_evaluation: true
    verbose: false
  
  verifier_config:
    execution:
      model_name: gpt-4o-mini
      temperature: 0.0
      max_tokens: 800
      timeout: 30
      max_retries: 3
      response_format: json
    retrieval:
      max_nodes: 8
      max_hops: 2
      similarity_threshold: 0.8
    enable_evaluation: true
    verbose: false
  
  summarizer_config:
    execution:
      model_name: gpt-4o-mini
      temperature: 0.1
      max_tokens: 1200
      timeout: 30
      max_retries: 3
      response_format: json
    retrieval:
      max_nodes: 10
      max_hops: 2
      similarity_threshold: 0.7
    enable_evaluation: true
    verbose: false
