# Dataset configuration - Simplified version

# Dataset creation
dataset_creation:
  output_dir: "data/run_files/datasets"
  save_format: "jsonl"  # jsonl, json, csv
  
  # Data splitting
  splits:
    train: 0.7
    validation: 0.15
    test: 0.15
  
  # Quality control
  min_quality_score: 0.5
  min_success_rate: 0.3
  balance_task_types: true
  balance_difficulties: true
  
  # Size limits
  max_total_samples: 5
  min_samples_per_type: 1




