# Evaluation configuration

evaluation:
  enabled: true
  save_detailed_metrics: true
  answer_quality:
    exact_match: true
    f1_score: true
  citation_quality:
    citation_f1: true
  reasoning_quality:
    reasoning_quality: true
  safety_evaluation:
    safety_compliance: true
  performance_evaluation:
    response_time: true
  thresholds:
    minimum_f1: 0.5
    minimum_citation_f1: 0.3
    maximum_response_time: 30.0
    minimum_safety_score: 0.8
