# Document Ingestion Configuration

# Text Cleaning Configuration
cleaning:
  remove_headers_footers: true
  remove_page_numbers: true
  normalize_whitespace: true
  remove_special_chars: false
  fix_encoding: true
  remove_urls: false
  remove_emails: false
  min_content_length: 20
  remove_duplicate_lines: true

# Chunk Configuration
chunking:
  enabled: true
  chunk_size: 1000
  overlap_size: 100
  min_chunk_size: 50
  max_chunk_size: 2000
  strategy: "semantic"  # semantic, hierarchical, fixed_size

# Parsing Configuration
parsing:
  pdf_extract_tables: true
  pdf_extract_images: true
  html_extract_links: true
  html_extract_images: true

# Image Processing Configuration
image_processing:
  save_images: true
  image_output_dir: "data/images"
  image_format: "png"  # png, jpg, jpeg
  max_image_size: 2048  # max width/height in pixels
  compress_images: true
  image_quality: 85  # for jpg compression (1-100)

# Image Storage Configuration
image_storage:
  enabled: true
  save_directory: "data/images"
  format: "png"  # png, jpg, jpeg
  max_size: 10485760  # 10MB max file size
  compress: true