# Document Ingestion Configuration

# Text Cleaning Configuration
cleaning:
  remove_headers_footers: true
  remove_page_numbers: true
  normalize_whitespace: true
  remove_special_chars: false
  fix_encoding: true
  remove_urls: false
  remove_emails: false
  min_content_length: 20
  remove_duplicate_lines: true

# Chunk Configuration
chunking:
  enabled: true
  chunk_size: 1000
  overlap_size: 100
  min_chunk_size: 50
  max_chunk_size: 2000
  strategy: "semantic"  # semantic, hierarchical, fixed_size

# Parsing Configuration
parsing:
  pdf_extract_tables: true
  pdf_extract_images: true
  html_extract_links: true
  html_extract_images: true

# Image Processing Configuration
image_processing:
  save_images: true
  image_format: "png"  # png, jpg, jpeg
  max_image_size: 2048  # max width/height in pixels
  compress_images: true
  image_quality: 85  # for jpg compression (1-100)



# Web Collection Configuration
web_collection:
  max_pages: 200  # 增加页面数量，确保收集更多页面
  timeout: 60  # 增加超时时间到60秒，适应慢速网站
  delay: 2.0  # 增加延迟，避免被反爬虫检测

  use_playwright: true  # Use Playwright if available, otherwise fallback to Selenium
  
  # Enhanced click simulation for JavaScript navigation
  enable_click_simulation: true  # Enable Playwright click simulation
  max_clickable_elements: 25  # 增加可点击元素数量，确保点击所有主要导航链接
  wait_after_click: 0.5  # 保持较短的等待时间
  click_simulation_depth: 10  # 增加点击模拟深度，探索更多页面
  
  # LLM-based intelligent crawling
  use_llm_crawling: false  # Disable LLM-based intelligent link selection for more comprehensive exploration
  llm_model_name: "gpt-4o-mini"  # LLM model to use for intelligent crawling
  llm_temperature: 0.3  # Temperature for LLM responses
  llm_max_tokens: 1000  # Maximum tokens for LLM responses
  llm_quality_threshold: 0.6  # Minimum quality threshold for LLM assessments
  
  # LLM-based website type detection (separate from crawling)
  use_llm_website_type_detection: false  # Enable LLM-based website type detection
  website_type_llm_model: "gpt-4o-mini"  # LLM model to use for website type detection
  website_type_llm_temperature: 0.1  # Lower temperature for more consistent classification
  
  # Description refinement using small seq2seq models
  use_description_refinement: false  # Disable description refinement, use rule-based descriptions
  description_refinement_model: "google/flan-t5-small"  # Model for refining element descriptions
  
  # Multi-step Exploration Configuration
  exploration:
    max_depth: 20  # 减少深度，只探索主要模块
    max_pages_per_depth: 15 # 减少每层页面数量，提高速度
    follow_external_links: false  # Whether to follow links to external domains
    skip_patterns:  # URLs to skip during exploration
      - "javascript:"
      - "mailto:"
      - "tel:"
      - "ftp://"
      - "/api/"
      - "/admin/"
      - "/login"
      - "/logout"
      - "/signup"
      - ".pdf"
      - ".doc"
      - ".docx"
      - ".xls"
      - ".xlsx"
      - ".zip"
      - ".jpg"
      - ".jpeg"
      - ".png"
      - ".gif"
      - ".mp4"
      - ".avi"
      - "/s?"  # Skip search result pages
      - "wd="  # Skip search query parameters
      - "sa="  # Skip search analytics parameters
      - "rsv_"  # Skip search result parameters
    
    # Link filtering configuration
    link_filtering:
      skip_anchor_only: true  # Skip links that are only anchors (e.g., "#section")
      allow_subdomains: true  # Allow links to subdomains of the same domain
      allowed_schemes: ["http", "https", ""]  # Allowed URL schemes
      max_links_per_page: 20  # Maximum links to evaluate per page